CREATE TABLE IF NOT EXISTS checkouts (
    id SERIAL PRIMARY KEY,
    userId int REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    productId int REFERENCES products (id) ON UPDATE CASCADE ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);